# Generated by Django 3.2.18 on 2023-06-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Логин клиента')),
                ('spent_money', models.PositiveBigIntegerField(verbose_name='Количество потраченных денег')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название камня')),
            ],
            options={
                'verbose_name': 'Камень',
                'verbose_name_plural': 'Камни',
            },
        ),
        migrations.CreateModel(
            name='StoneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stones', to='core.customer', verbose_name='Покупатель')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.stone', verbose_name='Камень')),
            ],
            options={
                'verbose_name': 'Купленный камень',
                'verbose_name_plural': 'Купленные камни',
            },
        ),
    ]
