# Generated by Django 3.2.18 on 2023-06-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='spent_money',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Количество потраченных денег'),
        ),
    ]
