# Generated by Django 3.2.18 on 2023-06-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customer_spent_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoneitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
